{% set name = "rice" %}
{% set version = "4.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jasonroelofs/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: fb34402bf0f79a900fa02bd7396a35d661165f0975a93aee902e89e59adf045c

build:
  number: 0
  noarch: generic

requirements:
  host:
    - ruby 3.*
  run:
    - ruby 3.*

test:
  commands:
    - test -f $PREFIX/include/rice/rice.hpp  # [unix]
    - test -f $PREFIX/include/rice/stl.hpp   # [unix]
    - if exist %LIBRARY_INC%\\rice.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_INC%\\stl.hpp (exit 0) else (exit 1)   # [win]

about:
  home: https://github.com/jasonroelofs/rice
  summary: 'Ruby Interface for C++ Extensions'
  description: |
    Rice is a C++ header-only library that serves dual purposes. First, it makes
    it much easier to create Ruby bindings for existing C++ libraries. Second,
    it provides an object oriented interface to Ruby's C API that makes it easy
    to embed Ruby and write Ruby extensions in C++.
  license: BSD-2-Clause
  license_file: COPYING
  doc_url: http://jasonroelofs.github.io/rice

extra:
  recipe-maintainers:
    - IsabelParedes
